### PR TITLE
Created Fall Guys Heart

### PR DESCRIPTION
**Pull request by jojobudiman**
So I created a Fall Guys Bean heart version with Persian Green color. Enjoy! ❤️ 😊

### CODE REVIEW

**Review by lukeocodes — CHANGES_REQUESTED** [review]
did you have any luck running the build command locally so it creates all the PNG alternatives?

**Comment by jojobudiman** [comment]
My bad, haven't run the build command yet. Will update on the next commit! 👍

**Review by lukeocodes — APPROVED** [review]
I'll accept it because it's really cool, but you used a PNG not a SVG source. Try find an SVG version and replace it inside the base SVG, then submit a PR to change it (don't forget to run the build)

**Comment by jojobudiman** [comment]
No problem. Wait what? I did put the SVG source inside the `src` folder before I did the run build. 🤔

**Comment by lukeocodes** [comment]
No, when you view the source of your SVG file it looks like this

```
<image style="overflow:visible;opacity:0.75;" width="257" height="257" xlink:href="data:image/png;base64,
```

This is the fallguy graphic inside the heart's path mask. If you find an SVG of the fallguy graphic, you can literally take its source code and replace this `<image` tag with it (more or less... don't include the `<svg` tags at either end)☝🏻

**Comment by jojobudiman** [comment]
Understandable! Thank you for the explanation 😊  
My bad for not looking at the inside 🥺  
I'll reupdate again on the next commit 👍

**Comment by jojobudiman** [comment]
Lmk if there are still any issues 👍

**Pull request merged**
